### ISSUE TITLE
*** 没有规则可制作目标“3rd/skynet_package/lualib/socket_proxy.lua”

### ISSUE THREAD

**Issue by ellisfan** [sundream/ggApp#2]
在ggApp/loginserver下执行make linux
*** 没有规则可制作目标“3rd/skynet_package/lualib/socket_proxy.lua”，由“lualib/socket_proxy.lua” 需求。 停止

**Comment by sundream** [comment]
你的submodule没有检出？，下拉项目需要用：cd ~ && git clone https://github.com/sundream/ggApp --recursive
